[[redirects]]
  from = "/apply/CIBCAventura"
  to = "https://pftraveldev.wpengine.com/apply/CIBCAventura"
  status = 301
  force = true

[[redirects]]
  from = "/apply/*"
  to = "https://pftraveldev.wpengine.com/apply/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200