 [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

 [[redirects]]
  from = "/apply/*"
  to = "https://pftraveldev.wpengine.com/apply/:splat"
  status = 301

  [[redirects]]
  from = "/ads.txt"
  to = "https://adstxt.mediavine.com/sites/prince-of-travel/ads.txt"
  status = 301
  force = true
  
