name: Schedule Netlify Build
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # This one runs at 1 PM UTC daily, which corresponds to 8 AM EST
    - cron: "0 13 * * *"
    # This one runs at 11 PM UTC daily, which corresponds to 6 PM EST
    # - cron: "0 23 * * *"
    - cron: "30 21 * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/66995f70b2a59435eb9e9337
